import type { ConditionNode, Row } from "../src/model/index.js";
import { type Answer, node, sparse } from "./verdict-of.js";

export const ABSENT = Symbol("absent");

export type OperatorCase = [name: string, value: unknown, answer: Answer];

export type OperatorSuite = {
	title: string;
	condition: ConditionNode<Row>;
	field: string;
	cases: OperatorCase[];
};

export const OPERATOR_SUITES: OperatorSuite[] = [
	{
		title: "eq on a string",
		condition: node("status", "eq", "published"),
		field: "status",
		cases: [
			["the same string", "published", "yes"],
			["another string", "draft", "no"],
			["the same word in another case", "Published", "no"],
			["a number", 5, "unknown"],
			["a boolean", true, "unknown"],
			["null", null, "no"],
			["undefined", undefined, "unknown"],
			["an absent field", ABSENT, "unknown"],
			["an object", {}, "unknown"],
			["an array holding the value", ["published"], "unknown"],
		],
	},
	{
		title: "eq on a number",
		condition: node("views", "eq", 10),
		field: "views",
		cases: [
			["the same number", 10, "yes"],
			["the same number as a bigint", 10n, "yes"],
			["another number", 11, "no"],
			["the number written as a string", "10", "unknown"],
			["NaN", Number.NaN, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "eq on a boolean",
		condition: node("secret", "eq", true),
		field: "secret",
		cases: [
			["the same boolean", true, "yes"],
			["the other boolean", false, "no"],
			["the boolean written as a string", "true", "unknown"],
			["a number", 1, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "ne on a boolean",
		condition: node("secret", "ne", true),
		field: "secret",
		cases: [
			["the same boolean", true, "no"],
			["the other boolean", false, "yes"],
			["the boolean written as a string", "true", "unknown"],
			["a number", 1, "unknown"],
			["null", null, "yes"],
			["undefined", undefined, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "eq on a date",
		condition: node("createdAt", "eq", 1000),
		field: "createdAt",
		cases: [
			["a Date at that moment", new Date(1000), "yes"],
			["the epoch number itself", 1000, "yes"],
			["a Date at another moment", new Date(2000), "no"],
			["an invalid Date", new Date(Number.NaN), "unknown"],
			["the moment written as a string", "1970-01-01T00:00:01.000Z", "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "eq on a date the rule holds as a Date",
		condition: node("createdAt", "eq", new Date(1000)),
		field: "createdAt",
		cases: [
			["another Date at that moment", new Date(1000), "yes"],
			["the epoch number of that moment", 1000, "yes"],
			["a Date at another moment", new Date(2000), "no"],
			["an invalid Date", new Date(Number.NaN), "unknown"],
		],
	},
	{
		title: "eq on a number past 2^53",
		condition: node("views", "eq", 2 ** 53),
		field: "views",
		cases: [
			["the same number as a bigint", 2n ** 53n, "yes"],
			["the next bigint, which no number can hold", 2n ** 53n + 1n, "no"],
			["the number before it", 2 ** 53 - 1, "no"],
		],
	},
	{
		title: "eq null",
		condition: node("status", "eq", null),
		field: "status",
		cases: [
			["null", null, "yes"],
			["a string", "draft", "no"],
			["an empty string", "", "no"],
			["a number", 5, "no"],
			["a boolean", false, "no"],
			["undefined", undefined, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "ne null",
		condition: node("status", "ne", null),
		field: "status",
		cases: [
			["null", null, "no"],
			["a string", "draft", "yes"],
			["an empty string", "", "yes"],
			["a number", 5, "yes"],
			["undefined", undefined, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "in a list that holds null",
		condition: node("status", "in", ["draft", null]),
		field: "status",
		cases: [
			["null", null, "yes"],
			["the string the list names", "draft", "yes"],
			["another string", "published", "no"],
			["a number", 5, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "nin a list that holds null",
		condition: node("status", "nin", ["draft", null]),
		field: "status",
		cases: [
			["null", null, "no"],
			["the string the list names", "draft", "no"],
			["another string", "published", "yes"],
			["a number", 5, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "eq NaN, a rule only a cast carries past its checks",
		condition: node("views", "eq", Number.NaN),
		field: "views",
		cases: [
			["a number", 10, "unknown"],
			["NaN", Number.NaN, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "ne NaN",
		condition: node("views", "ne", Number.NaN),
		field: "views",
		cases: [
			["a number", 10, "unknown"],
			["null", null, "yes"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "in a list that holds NaN",
		condition: node("views", "in", [Number.NaN, 10]),
		field: "views",
		cases: [
			["the number the list names", 10, "yes"],
			["another number", 11, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "gt NaN",
		condition: node("views", "gt", Number.NaN),
		field: "views",
		cases: [
			["a number", 10, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "eq an invalid Date",
		condition: node("createdAt", "eq", new Date(Number.NaN)),
		field: "createdAt",
		cases: [
			["a Date", new Date(1000), "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "has NaN",
		condition: node("tags", "has", Number.NaN),
		field: "tags",
		cases: [
			["an array of numbers", [1, 2], "unknown"],
			["an empty array", [], "no"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "ne",
		condition: node("status", "ne", "published"),
		field: "status",
		cases: [
			["the same string", "published", "no"],
			["another string", "draft", "yes"],
			["the same word in another case", "Published", "yes"],
			["a number", 5, "unknown"],
			["a boolean", true, "unknown"],
			["null", null, "yes"],
			["undefined", undefined, "unknown"],
			["an absent field", ABSENT, "unknown"],
			["an object", {}, "unknown"],
			["an array holding the value", ["published"], "unknown"],
		],
	},
	{
		title: "in",
		condition: node("status", "in", ["draft", "review"]),
		field: "status",
		cases: [
			["the first value in the list", "draft", "yes"],
			["the last value in the list", "review", "yes"],
			["a value outside the list", "published", "no"],
			["a number", 5, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
			["an object", {}, "unknown"],
			["an array holding a value from the list", ["draft"], "unknown"],
		],
	},
	{
		title: "in a list that holds a number",
		condition: node("status", "in", ["draft", 5]),
		field: "status",
		cases: [
			["the string the list names", "draft", "yes"],
			["the number the list names", 5, "yes"],
			["a string the list does not name", "published", "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "in a list that holds an object",
		condition: node("status", "in", ["draft", {}]),
		field: "status",
		cases: [
			["the value the list names", "draft", "yes"],
			["a value the list does not name", "published", "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "in an empty list",
		condition: node("status", "in", []),
		field: "status",
		cases: [
			["any value", "draft", "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "nin",
		condition: node("status", "nin", ["draft", "review"]),
		field: "status",
		cases: [
			["a value in the list", "draft", "no"],
			["a value outside the list", "published", "yes"],
			["a number", 5, "unknown"],
			["null", null, "yes"],
			["an absent field", ABSENT, "unknown"],
			["an object", {}, "unknown"],
			["an array holding a value from the list", ["draft"], "unknown"],
		],
	},
	{
		title: "nin an empty list",
		condition: node("status", "nin", []),
		field: "status",
		cases: [
			["any value", "draft", "yes"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "gt",
		condition: node("views", "gt", 10),
		field: "views",
		cases: [
			["a greater number", 11, "yes"],
			["a greater fraction", 10.5, "yes"],
			["an equal number", 10, "no"],
			["a smaller number", 9, "no"],
			["a greater bigint", 11n, "yes"],
			["a Date past that epoch", new Date(11), "yes"],
			["a number written as a string", "11", "unknown"],
			["a word", "abc", "unknown"],
			["NaN", Number.NaN, "unknown"],
			["a boolean", true, "unknown"],
			["an object", {}, "unknown"],
			["an array", [11], "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "gte",
		condition: node("views", "gte", 10),
		field: "views",
		cases: [
			["an equal number", 10, "yes"],
			["a greater number", 11, "yes"],
			["a smaller number", 9, "no"],
			["a number written as a string", "10", "unknown"],
			["NaN", Number.NaN, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "lt",
		condition: node("views", "lt", 10),
		field: "views",
		cases: [
			["a smaller number", 9, "yes"],
			["an equal number", 10, "no"],
			["a greater number", 11, "no"],
			["a number written as a string", "9", "unknown"],
			["NaN", Number.NaN, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "lte",
		condition: node("views", "lte", 10),
		field: "views",
		cases: [
			["an equal number", 10, "yes"],
			["a smaller number", 9, "yes"],
			["a greater number", 11, "no"],
			["a number written as a string", "10", "unknown"],
			["NaN", Number.NaN, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "gt on a string, which is compared by equality only",
		condition: node("title", "gt", "b"),
		field: "title",
		cases: [
			["a later string", "c", "unknown"],
			["the same string", "b", "unknown"],
			["an earlier string", "a", "unknown"],
			["null", null, "no"],
			["a number", 5, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "gt on a date",
		condition: node("createdAt", "gt", 1000),
		field: "createdAt",
		cases: [
			["a later Date", new Date(2000), "yes"],
			["an earlier Date", new Date(500), "no"],
			["a later epoch number", 2000, "yes"],
			["an invalid Date", new Date(Number.NaN), "unknown"],
			["a date written as a string", "2000", "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "contains",
		condition: node("title", "contains", "ell"),
		field: "title",
		cases: [
			["a string holding the substring", "hello", "yes"],
			["the substring in another case", "HELLO", "no"],
			["a string without it", "help", "no"],
			["an empty string", "", "no"],
			["a number", 5, "unknown"],
			["an array holding a matching string", ["hello"], "unknown"],
			["an object", {}, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "exists true",
		condition: node("status", "exists", true),
		field: "status",
		cases: [
			["a string", "draft", "yes"],
			["an empty string", "", "yes"],
			["zero", 0, "yes"],
			["false", false, "yes"],
			["an object", {}, "yes"],
			["null", null, "no"],
			["undefined", undefined, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "exists false",
		condition: node("status", "exists", false),
		field: "status",
		cases: [
			["a string", "draft", "no"],
			["an empty string", "", "no"],
			["zero", 0, "no"],
			["null", null, "yes"],
			["undefined", undefined, "unknown"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "has",
		condition: node("tags", "has", "x"),
		field: "tags",
		cases: [
			["an array holding the element", ["x", "y"], "yes"],
			["an array holding it after an object", [{}, "x"], "yes"],
			["an array holding it after a hole", sparse(2, { 1: "x" }), "yes"],
			["an array of holes", sparse(2, {}), "no"],
			["an array without it", ["y"], "no"],
			["an array holding null", [null], "no"],
			["an empty array", [], "no"],
			["an array holding only a number", [5], "unknown"],
			["an array holding it after a number", [5, "x"], "yes"],
			["an array holding only an object", [{}], "unknown"],
			["the element itself, not in an array", "x", "unknown"],
			["an object", {}, "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "hasAny",
		condition: node("tags", "hasAny", ["x", "z"]),
		field: "tags",
		cases: [
			["an array holding one of them", ["x"], "yes"],
			["an array holding the other", ["y", "z"], "yes"],
			[
				"an array holding one of them after a hole",
				sparse(2, { 1: "z" }),
				"yes",
			],
			["an array of holes", sparse(2, {}), "no"],
			["an array holding neither", ["y"], "no"],
			["an empty array", [], "no"],
			["an array holding only a number", [5], "unknown"],
			["an array holding only a boolean", [true], "unknown"],
			["an array holding only an object", [{}], "unknown"],
			["one of them, not in an array", "x", "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "hasAny of an empty list",
		condition: node("tags", "hasAny", []),
		field: "tags",
		cases: [
			["any array", ["x"], "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "hasAll",
		condition: node("tags", "hasAll", ["x", "y"]),
		field: "tags",
		cases: [
			["an array holding both and more", ["x", "y", "z"], "yes"],
			["an array holding both in another order", ["y", "x"], "yes"],
			[
				"an array holding both around a hole",
				sparse(3, { 0: "x", 2: "y" }),
				"yes",
			],
			["an array holding one and holes", sparse(3, { 1: "x" }), "no"],
			["an array holding one", ["x"], "no"],
			["an empty array", [], "no"],
			["an array holding one and a number", ["x", 5], "unknown"],
			["an array holding one and an object", ["x", {}], "unknown"],
			["one of them, not in an array", "x", "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
	{
		title: "hasAll of an empty list",
		condition: node("tags", "hasAll", []),
		field: "tags",
		cases: [
			["an empty array", [], "yes"],
			["any array", ["z"], "yes"],
			["an array of holes", sparse(2, {}), "yes"],
			["something that is not an array", "x", "unknown"],
			["null", null, "no"],
			["an absent field", ABSENT, "unknown"],
		],
	},
];
